### ISSUE TITLE
Test unpickling nested higher kinded types

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/scala#11]
**[1 hour]**

create test case that will exercise nested higher kinded types, in both type aliases and type parameters, and also try with bounds and variance

**Comment by errikos** [comment]
Here's a commit with a test throwing a type mismatch error: https://github.com/scalacenter/scala/commit/6e98e6ad9ee00f368edd64926989c0dacf8e552c

It fails with:
```
TestHKNest.scala:10: error: no type parameters for method foo: (x: tastytest.HKNest.Foo[F])String exist so that it can be applied to arguments (tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]])
 --- because ---
argument expression's type is not compatible with formal parameter type;
 found   : tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]]
 required: tastytest.HKNest.Foo[?F]30s

    test(assert(new Consume[Foo].foo(new Foo[Box]) == "Foo"))
                                 ^
TestHKNest.scala:10: error: type mismatch;
 found   : tastytest.HKNest.Foo[tastytest.HKNest.Box[_$8]]
 required: tastytest.HKNest.Foo[F]
    test(assert(new Consume[Foo].foo(new Foo[Box]) == "Foo"))
                                     ^
2 errors
```

**Comment by bishabosha** [comment]
Thank you :)

**Comment by bishabosha** [comment]
It appears that the issue is that the type of the primary constructor of Foo when unpicked from tasty is returning a `Foo[F[_$1]]` rather than `Foo[F]`. However the type of the `Foo` class is `Foo[F]`
